---
name: Build App

on:
  push:
    branches:
      - souce

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.0.0
      - name: npm install, build, and test
        run: |
          yarn build --production
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update page"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

